name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🐞 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🤖 Dependencies"
    labels:
      - "dependency"
change-template: "- $TITLE (#$NUMBER)"
template: |
  ## 🚀 Features and improvemens

  $CHANGES
