name: Release Drafter

on:
  push:
    branches:
      - staging

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          # This secret is available by default
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
